[package]
name = "elementtree"
version = "0.6.0"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]
description = "Parse an XML file into Python elementtree like structure"
documentation = "http://docs.rs/elementtree"
repository = "https://github.com/mitsuhiko/elementtree-rust"
keywords = ["xml", "parse", "elementtree"]
license = "BSD-3-Clause"
readme = "README.md"
edition = "2018"

[dependencies]
xml-rs = "0.8"
string_cache = "0.8"
